---
title: Geometri og trigonometri
format:
  pdf:
    colorlinks: true
---

## Trekanten

- størrelser
- *hjørner*, *vinkelspidser*, *sider*
- *Højder*, *medianer*, *vinkelhalveringslinjer*

### Den retvinklede trekant

- *Kateter*, *hypotenusen*
- **Pythagoras' læresætning**
    - bevis 

### Ensvinklede trekanter

- *ensvinklede*, *ligedannede*
- *målestoksoforholdet*, *proportionale*


## Cosinus, sinus og tangens

- Enhedscirklen
- Definition af cosinus, sinus og tangens
- sammenhæng mellem cosinus, sinus og tangens

### Enhedscirklen

- definitionen
- *retningspunkt P*

### Cosinus, sinus og tangens

- definitionen og omløbretninger
- vinkler med fortegn
- **grundrelationen**
- *Radianer* og *grader*

-------------------------


### Arealet af en vilkårlig trekant

- Sætning 3.5.1
- Eksempel 3.5.1

### Cirklens omkreds og areal

- Sætning 3.6.1.1

### Vinkler i tilknytning til cirklen

- Centervinkel
- Periferivinkel
- Sætning 3.6.2.1

----

### Tangent

- Definitionen
    - cirkelbue
    - tangerer
    - tangentpunktet

### Korde

- Definitionen
- sætning 3.6.4.1

### Pilhøjde

- Definitionen
- Sætning 3.6.5.1

----


### Sammenhæng mellem radius, pilhøjde og korde

- Sætning 3.6.6.1
- Eksempel 3.6.6.1


### Cirkeludsnit

- Definitionen
- Sætning 3.6.7.1

----

### Cirkelbue

- Sætning 3.6.8.1
- Eksempel 3.6.8.1 

### Cirkelafsnit

- Definitionen
- Sætning 3.6.9.1
- Eksempel 3.6.9.1

----
## Den indskrevne cirkel

- Definitionen
- Sætning 3.6.10.1

## Den omskrevne cirkel og den regulære polygon

- Sætning 3.6.11.1
- Sætning 3.6.11.2
- Eksempel 3.6.11.1